
[warpwing-item]
	#Time in ticks it takes to charge up the wing before using it
	#Range: > 1
	"Value must be at least 1" = 40
	#Durability of the warp wing item
	#Range: > 1
	"Uses of the warp wing, muse be at least 0" = 16

